Fix CI 3

diff --git a/.github/workflows/lighthouse.yml b/.github/workflows/lighthouse.yml
--- a/.github/workflows/lighthouse.yml
+++ b/.github/workflows/lighthouse.yml
@@ -5,24 +5,32 @@ on: [pull_request]
 jobs:
   build:
     runs-on: ubuntu-latest
-    outputs:
-        deploy_url: ${{ steps.wait-for-netflify-preview.outputs.deploy_url }}
+
     steps:
+      - uses: actions/checkout@v2
+      - uses: actions/setup-node@v1
       - name: Wait for Netlify
         uses: JakePartusch/wait-for-netlify-action@v1.2
         id: wait-for-netflify-preview
         with:
           site_name: "evertonstrack"
           max_timeout: "120"
-        run: echo "::set-output name=deploy_url::${{ steps.wait-for-netflify-preview.outputs.url }}
+      - name: Lighthouse CI
+        run: |
+            npm install -g @lhci/cli@0.6.x
+            lhci autorun --upload.target=temporary-public-storage --collect.url=${{ steps.wait-for-netflify-preview.outputs.url }} || echo "LHCI failed!"
+        env:
+          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
+
   lighthouseci:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-node@v1
-      - name: Lighthouse CI
-        run: |
-            npm install -g @lhci/cli@0.6.x
-            lhci autorun --upload.target=temporary-public-storage --collect.url=${{ needs.build.deploy_url }} || echo "LHCI failed!"
+      - name: Setup Lighthouse CI
+      - name: Install Lighthouse CI
+        run: npm install -g @lhci/cli@0.6.x
+      - name: Run Lighthouse CI
+        run: lhci autorun --upload.target=temporary-public-storage --collect.url=${{ needs.build.deploy_url }} || echo "LHCI failed!"
         env:
           LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
