Fix deploy 1

diff --git a/.github/workflows/web_performance.yml b/.github/workflows/web_performance.yml
--- a/.github/workflows/web_performance.yml
+++ b/.github/workflows/web_performance.yml
@@ -6,6 +6,8 @@ jobs:
   build:
     name: Wait for Netlify build preview
     runs-on: ubuntu-latest
+    outputs:
+        deploy_url: ${{ steps.wait-for-netflify-preview.outputs.deploy_url }}
     steps:
       - uses: actions/checkout@v2
       - name: Wait for Netlify
@@ -14,6 +16,7 @@ jobs:
         with:
           site_name: "evertonstrack"
           max_timeout: "120"
+        run: echo "::set-output name=deploy_url::${{ steps.wait-for-netflify-preview.outputs.url }}
   performance_audit:
     name: Performance Audit
     needs: build
@@ -24,7 +27,7 @@ jobs:
         uses: justinribeiro/lighthouse-action@master
         with:
           secret: ${{ secrets.GITHUB_TOKEN }}
-          url: ${{ build.steps.wait-for-netflify-preview.outputs.url }}
+          url: ${{ needs.build.deploy_url }}
           wptConnectionSpeed: threegfast
       - name: Saving Lighthouse Audit Artifacts
         uses: actions/upload-artifact@master
@@ -42,6 +45,6 @@ jobs:
       - name: Lighthouse CI - Audit
         run: |
             npm install -g @lhci/cli@0.6.x
-            lhci autorun --upload.target=temporary-public-storage --collect.url=${{ build.steps.wait-for-netflify-preview.outputs.url }} || echo "LHCI failed!"
+            lhci autorun --upload.target=temporary-public-storage --collect.url=${{ needs.build.deploy_url }} || echo "LHCI failed!"
         env:
           LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
