Fix CI 2

diff --git a/.github/workflows/web_performance.yml b/.github/workflows/web_performance.yml
--- a/.github/workflows/web_performance.yml
+++ b/.github/workflows/web_performance.yml
@@ -3,13 +3,9 @@ name: Web Performance
 on: [pull_request]
 
 jobs:
-  strategy:
-    max-parallel: 1
   build:
     name: Wait for Netlify build preview
     runs-on: ubuntu-latest
-    outputs:
-      deploy_url: ${{ steps.wait-for-netflify-preview.outputs.deploy_url }}
     steps:
       - name: Wait for Netlify
         uses: JakePartusch/wait-for-netlify-action@v1.2
@@ -17,8 +13,6 @@ jobs:
         with:
           site_name: "evertonstrack"
           max_timeout: "120"
-      - name: Set URL
-        run: echo "::set-output name=deploy_url::${{ steps.wait-for-netflify-preview.outputs.url }}
   performance_audit:
     name: Performance Audit
     needs: build
@@ -29,7 +23,7 @@ jobs:
         uses: justinribeiro/lighthouse-action@master
         with:
           secret: ${{ secrets.GITHUB_TOKEN }}
-          url: ${{ needs.build.deploy_url }}
+          url: ${{ jobs.build.steps.wait-for-netflify-preview.outputs.url }}
           wptConnectionSpeed: threegfast
       - name: Saving Lighthouse Audit Artifacts
         uses: actions/upload-artifact@master
@@ -48,6 +42,6 @@ jobs:
       - name: Lighthouse CI - Audit
         run: |
             npm install -g @lhci/cli@0.6.x
-            lhci autorun --upload.target=temporary-public-storage --collect.url=${{ needs.build.deploy_url }} || echo "LHCI failed!"
+            lhci autorun --upload.target=temporary-public-storage --collect.url=${{ jobs.build.steps.wait-for-netflify-preview.outputs.url }} || echo "LHCI failed!"
         env:
           LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
